server:
  servlet:
    context-path: "/mono"
  port: 9090
  session:
    cookie:
      name: SSHSESSIONID

spring:
  profiles:
    active:
      - kafka
      - local
  redis:
    host: localhost
    port: 6379
  session:
    store-type: redis
    redis.namespace: spring:mono:session

management: # Actuator
  endpoints:
    web:
      exposure:
        include: "*"